---
driver:
  name: vagrant
  synced_folders:
    - ["./", "/tmp/package"]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2016
    driver_config:
      box: mwrock/Windows2016


suites:
  - name: default
    run_list:
      - recipe[windows-habitat-no-docker::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
